version: '3.9'

networks:
  spark_network:
    driver: bridge  # Ensure this network is defined

# volumes:
#   spark-jars:

x-airflow-common:
  &airflow-common
  build:
    context: ./airflow/
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW_CONN_POSTGRES_DEFAULT: postgres://airflow:airflow@postgres:5432/airflow
    AIRFLOW__CORE__TEST_CONNECTION: Enabled
    PYTHONPATH: /opt/airflow/src
  env_file:
    - ./airflow/airflow.env
  volumes:
    - ${AIRFLOW_DAGS}:/opt/airflow/dags
    - ${AIRFLOW_LOGS}:/opt/airflow/logs
    - ${AIRFLOW_PLUGINS}:/opt/airflow/plugins
    - ${AIRFLOW_SECRETS}:/opt/secrets
    - ${AIRFLOW_DATA}:/opt/airflow/data
    - ${AIRFLOW_PYTHONPATH}:/opt/airflow/src
    - ${AIRFLOW_SPARK}:/opt/airflow/spark
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    postgres:
      condition: service_healthy
  networks:
    - spark_network

x-spark-common: &spark-common
  build:
    context: ./spark
    dockerfile: Dockerfile
  volumes:
    - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    # - spark-jars:/opt/bitnami/spark/jars
    - ./spark/jobs:/opt/bitnami/spark/jobs
  networks:
    - spark_network
  environment:
    SPARK_RPC_AUTHENTICATION_ENABLED: no
    SPARK_RPC_ENCRYPTION_ENABLED: no
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
    SPARK_SSL_ENABLED: no
  env_file:
    - ./spark.env

services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    restart: always
    ports:
      - "5433:5432"
    networks:
      - spark_network

  airflow-webserver:
    <<: *airflow-common
    container_name: webserver
    command: webserver
    ports:
      - 8081:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: scheduler
    command: scheduler
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow

  minio:
    hostname: minio
    image: "minio/minio"
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: [ "server", "/data", "--console-address", ":9001" ]
    networks:
      - spark_network

  spark-master:
    <<: *spark-common
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      SPARK_MODE: master
      SPARK_LOCAL_IP: spark-master
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./spark/jobs:/opt/bitnami/spark/jobs

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 2g
    # deploy:
    #   replicas: 2

  spark-notebook:
    build:
      context: ./notebooks
      dockerfile: ./Dockerfile
    container_name: "spark-notebook"
    user: root
    environment:
      - JUPYTER_ENABLE_LAB="yes"
      - GRANT_SUDO="yes"
    env_file:
      - ./spark.env
    volumes:
      - ./notebooks/work:/home/jovyan/work
      - ./notebooks/spark-defaults.conf:/usr/local/spark/conf/spark-defaults.conf
    ports:
      - "8888:8888"
      - "4040:4040"
    networks:
      - spark_network

  # dbt Service for Data Transformation
  # dbt:
  #   image: ghcr.io/dbt-labs/dbt-postgres:1.8.2
  #   container_name: dbt
  #   volumes:
  #     # - ./dbt:/usr/app
  #     - ./dbt/project:/usr/app
  #     - ./dbt/profiles.yml:/root/.dbt/profiles.yml
  #   working_dir: /usr/app
  #   environment:
  #     DBT_PROFILES_DIR: /usr/app
  #   # entrypoint: ["dbt"]  # Set entry point to dbt (default: dbt)
  #   # command: ["run"]     # Command to run after entry point
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
